[package]
name = "godot_audio_kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.1"
gdnative = "0.10.1"

[lib]
crate-type = ["cdylib"]
