name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: sudo apt install llvm clang
    - name: Build
      run: cargo build --verbose --release
    - name: Upload Result
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: libgodot_audio_kit.so
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/libgodot_audio_kit.so
  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: brew install rust
    - name: Build
      run: cargo build --verbose --release
    - name: Upload Result
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: libgodot_audio_kit.dylib
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/libgodot_audio_kit.dylib
